Models/Category.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Supplier.Models
{
    public class Category : BaseEntity
    {
        public int Id { get; set;  }
        public string Description { get; set; }
        public string Name { get; set; }
        public List<CategoryProduct> Products { get; set; }
        public List<CategorySpecification> CategorySpecifications { get; set; }
        [NotMapped]
        [DisplayName("Upload File")]
        public IFormFile ImageFile { get; set; }
        public List<Image> images { get; set; }



    }
}

Controllers/CategoryProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Supplier.Models;

namespace Supplier.Controllers
{
    [Authorize]
    public class CategoryProductsController : Controller
    {
        private readonly SupplierDbContext _context;

        public CategoryProductsController(SupplierDbContext context)
        {
            _context = context;
        }

        // GET: CategoryProducts
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var supplierDbContext = _context.CategoryProducts.Include(c => c.Category).Include(c => c.Product);
            return View(await supplierDbContext.ToListAsync());
        }

        // GET: CategoryProducts/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categoryProduct = await _context.CategoryProducts
                .Include(c => c.Category)
                .Include(c => c.Product)
                .FirstOrDefaultAsync(m => m.CategoryId == id);
            if (categoryProduct == null)
            {
                return NotFound();
            }

            return View(categoryProduct);
        }

        // GET: CategoryProducts/Create
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name");
            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Name");
            return View();
        }
        public IActionResult CreateWithCategoryId(int id)
        {
            var x = new CategoryProduct();
            x.CategoryId = id;
            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Name");
            return View(x);
        }
       

        // POST: CategoryProducts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CategoryId,ProductId")] CategoryProduct categoryProduct)
        {
            if (ModelState.IsValid)
            {
                _context.Add(categoryProduct);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Id", categoryProduct.CategoryId);
            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Id", categoryProduct.ProductId);
            return View(categoryProduct);
        }
        /*
         * 
         * 
         * 
         * 
         * 
         */
          // POST: CategoryProducts/CreateWithCategoryId
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateWithCategoryId([Bind("CategoryId,ProductId")] CategoryProduct categoryProduct)
        {

            if (ModelState.IsValid)
            {
                categoryProduct.ProductId = 0;
                _context.Add(categoryProduct);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Id", categoryProduct.CategoryId);
            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Id", categoryProduct.ProductId);
            return View(categoryProduct);
        }

         /* 
         * 
         * 
         * 
         * 
         * 
         * 
         * */
        // GET: CategoryProducts/Edit/5
        public async Task<IActionResult> Edit(int CategoryId , int ProductId)
        {
            //if (id == null)
            //{
            //    return NotFound();
            //}

            var categoryProduct = await _context.CategoryProducts.FirstOrDefaultAsync(m => m.ProductId==ProductId && m.CategoryId==CategoryId);
            if (categoryProduct == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Id", categoryProduct.CategoryId);
            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Id", categoryProduct.ProductId);
            return View(categoryProduct);
        }

        // POST: CategoryProducts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int CategoryId, int ProductId,[Bind("CategoryId,ProductId")] CategoryProduct categoryProduct)
        {
            //if (CategoryId != categoryProduct.CategoryId)
            //{
            //    return NotFound();
            //}

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(categoryProduct);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryProductExists(categoryProduct.CategoryId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Id", categoryProduct.CategoryId);
            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Id", categoryProduct.ProductId);
            return View(categoryProduct);
        }

        // GET: CategoryProducts/Delete/5
        public async Task<IActionResult> Delete(int CategoryId, int ProductId)
        {
           
         

            var categoryProduct = await _context.CategoryProducts
                .Include(c => c.Category)
                .Include(c => c.Product)
                .FirstOrDefaultAsync(m =>( m.CategoryId == CategoryId&& ProductId==m.ProductId));
            if (categoryProduct == null)
            {
                return NotFound();
            }

            return View(categoryProduct);
        }

        // POST: CategoryProducts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int CategoryId, int ProductId)
        {
            var categoryProduct = await _context.CategoryProducts.FirstOrDefaultAsync(m => (m.CategoryId == CategoryId && ProductId == m.ProductId));
            _context.CategoryProducts.Remove(categoryProduct);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryProductExists(int id)
        {
            return _context.CategoryProducts.Any(e => e.CategoryId == id);
        }
    }
}

Controllers/CategorySpecificationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Supplier.Models;

namespace Supplier.Controllers
{
    [Authorize]
    public class CategorySpecificationsController : Controller
    {
        private readonly SupplierDbContext _context;

        public CategorySpecificationsController(SupplierDbContext context)
        {
            _context = context;
        }

        // GET: CategorySpecifications
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var supplierDbContext = _context.CategorySpecifications.Include(c => c.Category);
            return View(await supplierDbContext.ToListAsync());
        }

        [AllowAnonymous]
        public async Task<IActionResult> IndexForId(int id)
        {
            var supplierDbContext = _context.CategorySpecifications.Where(p => p.CategoryId == id);
            supplierDbContext = supplierDbContext.Include(m => m.Category);
            //return RedirectToAction("Index", "ProductSpecifications");
            return View("Index", await supplierDbContext.ToListAsync());
        }

        // GET: CategorySpecifications/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categorySpecification = await _context.CategorySpecifications
                .Include(c => c.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (categorySpecification == null)
            {
                return NotFound();
            }

            return View(categorySpecification);
        }

        // GET: CategorySpecifications/Create
        /*public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name");
            return View();
        }*/

        public IActionResult Create(int id)
        {
            var x = new CategorySpecification();
            x.CategoryId = id;
            ViewData["CategoryId"] = _context.Categories.FirstOrDefault(m => m.Id == id).Id;
            return View(x);
        }

        // POST: CategorySpecifications/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,isValued,CategoryId")] CategorySpecification categorySpecification)
        {
            if (ModelState.IsValid)
            {
                categorySpecification.Id = 0;
                _context.Add(categorySpecification);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Categories");
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Id", categorySpecification.CategoryId);
            return View(categorySpecification);
        }

        // GET: CategorySpecifications/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categorySpecification = await _context.CategorySpecifications.FindAsync(id);
            if (categorySpecification == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", categorySpecification.CategoryId);
            return View(categorySpecification);
        }
              
        // POST: CategorySpecifications/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,isValued,CategoryId")] CategorySpecification categorySpecification)
        {
          
            if (id != categorySpecification.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(categorySpecification);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategorySpecificationExists(categorySpecification.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Id", categorySpecification.CategoryId);
            return View(categorySpecification);
        }

        // GET: CategorySpecifications/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categorySpecification = await _context.CategorySpecifications
                .Include(c => c.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (categorySpecification == null)
            {
                return NotFound();
            }

            return View(categorySpecification);
        }

        // POST: CategorySpecifications/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var categorySpecification = await _context.CategorySpecifications.FindAsync(id);
            _context.CategorySpecifications.Remove(categorySpecification);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategorySpecificationExists(int id)
        {
            return _context.CategorySpecifications.Any(e => e.Id == id);
        }
    }
}

Views/Categories/Create.cshtml
@model Supplier.Models.Category

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/NavbarAdmin.cshtml";
}

    <h1>Create new Category</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input required asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input required asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="ImageFile" class="control-label"></label>
                <input required asp-for="ImageFile" accept="image/*" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
                <a class="btn btn-primary" asp-action="Index" style="
                        color: white;">Back to List</a>
            </div>
        </form>
    </div>
</div>

Views/Categories/Delete.cshtml
@model Supplier.Models.Category

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/NavbarAdmin.cshtml";}

<h4>Deleting Category: @Html.DisplayFor(model => model.Name)</h4>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Categories/Details.cshtml
@model Supplier.Models.Category

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/NavbarAdmin.cshtml";}

<h4>Details for Category: @Html.DisplayFor(model => model.Name)</h4>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Categories/Edit.cshtml
@model Supplier.Models.Category

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/NavbarAdmin.cshtml";
}

<h4>Editing Category: @Html.DisplayFor(model => model.Name)</h4>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Categories/Index.cshtml
@model IEnumerable<Supplier.Models.Category>

@{
    ViewData["Title"] = "Categories";
    Layout = "~/Views/Shared/NavbarAdmin.cshtml";}


<p>
    <a class="btn btn-primary" asp-action="Create">Create New Category</a>
</p>
<div id="dataDiv" style=" margin-left:10px; padding:5px;">
    <table id="customerDatatable" class="table table-striped table-bordered dt-responsive nowrap" width="100%" cellspacing="0">
        <thead>
            <tr>
                <th>
                    Category Name
                </th>
                <th>
                    Description
                </th>

                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>

                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">
                            <i class="far fa-edit fa-lg text-dark"></i><!--For Edit-->
                        </a> |
                        <a asp-action="Details" asp-route-id="@item.Id">
                            <i style="color:blue;" class="far fa-lg fa-question-circle"></i><!--For Details-->
                        </a>  |
                        <a asp-action="Delete" asp-route-id="@item.Id">
                             <i class="far fa-trash-alt fa-lg text-danger"></i><!--For Delete-->
                        </a> |
                        <a asp-action="CreateWithCategoryId" asp-controller="CategoryProducts" asp-route-id="@item.Id">Add Product</a> |
                        <a asp-action="Create" asp-controller="Product" asp-route-id="@item.Id">Show Products</a> |
                        <a asp-action="Create" asp-controller="CategorySpecifications" asp-route-id="@item.Id">Add Specification</a> |
                        <a asp-action="IndexForId" asp-controller="CategorySpecifications" asp-route-id="@item.Id">Show Specifications</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
@section Scripts
{
    <script src="~/lib/datatables/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/datatables/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/js/customerDatatable.js"></script>
    <script>
        $(document).ready(function () {
            $('#customerDatatable').dataTable({
            });
        });</script>
}