Models/CategoryProduct.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Supplier.Models
{
    public class CategoryProduct : BaseEntity
    {
        public int CategoryId { get; set; }
        public Category Category { get; set; }
        public int ProductId { get; set; }
        public Product Product { get; set; }
    }
}

Models/Product.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Supplier.Models
{
    public class Product : BaseEntity
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public DateTime ProductionDate { get; set; }
        public DateTime ExpireDate { get; set; }

        public int Amount { get; set; }

        public int Price { get; set; }
        public string ImageName { get; set; }
        public string ImagePath { get; set; }
        public  List<CategoryProduct> Categories { get; set; }
        public List<ProductSpecification> ProductSpecifications { get; set; }
        public List<Specification> Specifications { get; set; }
      //image
       
        [NotMapped]
        [DisplayName("Upload File")]
        public IFormFile ImageFile { get; set; }


    }
}

Controllers/CategoryProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Supplier.Models;

namespace Supplier.Controllers
{
    [Authorize]
    public class CategoryProductsController : Controller
    {
        private readonly SupplierDbContext _context;

        public CategoryProductsController(SupplierDbContext context)
        {
            _context = context;
        }

        // GET: CategoryProducts
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var supplierDbContext = _context.CategoryProducts.Include(c => c.Category).Include(c => c.Product);
            return View(await supplierDbContext.ToListAsync());
        }

        // GET: CategoryProducts/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categoryProduct = await _context.CategoryProducts
                .Include(c => c.Category)
                .Include(c => c.Product)
                .FirstOrDefaultAsync(m => m.CategoryId == id);
            if (categoryProduct == null)
            {
                return NotFound();
            }

            return View(categoryProduct);
        }

        // GET: CategoryProducts/Create
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name");
            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Name");
            return View();
        }
        public IActionResult CreateWithCategoryId(int id)
        {
            var x = new CategoryProduct();
            x.CategoryId = id;
            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Name");
            return View(x);
        }
       

        // POST: CategoryProducts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CategoryId,ProductId")] CategoryProduct categoryProduct)
        {
            if (ModelState.IsValid)
            {
                _context.Add(categoryProduct);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Id", categoryProduct.CategoryId);
            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Id", categoryProduct.ProductId);
            return View(categoryProduct);
        }
        /*
         * 
         * 
         * 
         * 
         * 
         */
          // POST: CategoryProducts/CreateWithCategoryId
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateWithCategoryId([Bind("CategoryId,ProductId")] CategoryProduct categoryProduct)
        {

            if (ModelState.IsValid)
            {
                categoryProduct.ProductId = 0;
                _context.Add(categoryProduct);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Id", categoryProduct.CategoryId);
            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Id", categoryProduct.ProductId);
            return View(categoryProduct);
        }

         /* 
         * 
         * 
         * 
         * 
         * 
         * 
         * */
        // GET: CategoryProducts/Edit/5
        public async Task<IActionResult> Edit(int CategoryId , int ProductId)
        {
            //if (id == null)
            //{
            //    return NotFound();
            //}

            var categoryProduct = await _context.CategoryProducts.FirstOrDefaultAsync(m => m.ProductId==ProductId && m.CategoryId==CategoryId);
            if (categoryProduct == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Id", categoryProduct.CategoryId);
            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Id", categoryProduct.ProductId);
            return View(categoryProduct);
        }

        // POST: CategoryProducts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int CategoryId, int ProductId,[Bind("CategoryId,ProductId")] CategoryProduct categoryProduct)
        {
            //if (CategoryId != categoryProduct.CategoryId)
            //{
            //    return NotFound();
            //}

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(categoryProduct);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryProductExists(categoryProduct.CategoryId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Id", categoryProduct.CategoryId);
            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Id", categoryProduct.ProductId);
            return View(categoryProduct);
        }

        // GET: CategoryProducts/Delete/5
        public async Task<IActionResult> Delete(int CategoryId, int ProductId)
        {
           
         

            var categoryProduct = await _context.CategoryProducts
                .Include(c => c.Category)
                .Include(c => c.Product)
                .FirstOrDefaultAsync(m =>( m.CategoryId == CategoryId&& ProductId==m.ProductId));
            if (categoryProduct == null)
            {
                return NotFound();
            }

            return View(categoryProduct);
        }

        // POST: CategoryProducts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int CategoryId, int ProductId)
        {
            var categoryProduct = await _context.CategoryProducts.FirstOrDefaultAsync(m => (m.CategoryId == CategoryId && ProductId == m.ProductId));
            _context.CategoryProducts.Remove(categoryProduct);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryProductExists(int id)
        {
            return _context.CategoryProducts.Any(e => e.CategoryId == id);
        }
    }
}

Controllers/ProductSpecificationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Supplier.Models;

namespace Supplier.Controllers
{
    [Authorize]
    public class ProductSpecificationsController : Controller
    {
        private readonly SupplierDbContext _context;

        public ProductSpecificationsController(SupplierDbContext context)
        {
            _context = context;
        }

        // GET: ProductSpecifications
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var supplierDbContext = _context.ProductSpecifications.Include(p => p.Product);
            return View(await supplierDbContext.ToListAsync());
        }
        [AllowAnonymous]
        public async Task<IActionResult> IndexForId(int id)
        {
            
            var supplierDbContext = _context.ProductSpecifications.Where(p => p.Product.Id == id);
            supplierDbContext = supplierDbContext.Include(m=> m.Product);
            //return RedirectToAction("Index", "ProductSpecifications");
            return View("Index",await supplierDbContext.ToListAsync());
        }

        // GET: ProductSpecifications/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productSpecification = await _context.ProductSpecifications
                .Include(p => p.Product)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (productSpecification == null)
            {
                return NotFound();
            }

            return View(productSpecification);
        }

        // GET: ProductSpecifications/Create
        public IActionResult Create(int id)
        {
            var x = new ProductSpecification();
            x.ProductId = id;
            ViewData["ProductId"] = _context.Products.FirstOrDefault(m=>m.Id==id).Id;
            return View(x);
        }

        // POST: ProductSpecifications/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,name,value,ProductId")] ProductSpecification productSpecification)
        {
            if (ModelState.IsValid)
            {
                productSpecification.Id = 0;
                _context.Add(productSpecification);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Products");
            }
            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Id", productSpecification.ProductId);
            return RedirectToAction("Index","Products");
                //View(productSpecification);
        }

        // GET: ProductSpecifications/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productSpecification = await _context.ProductSpecifications.FindAsync(id);
            if (productSpecification == null)
            {
                return NotFound();
            }
            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Name", productSpecification.Id);
            return View(productSpecification);
        }

        // POST: ProductSpecifications/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,name,value,ProductId")] ProductSpecification productSpecification)
        {
            if (id != productSpecification.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(productSpecification);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductSpecificationExists(productSpecification.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Id", productSpecification.ProductId);
            return View(productSpecification);
        }

        // GET: ProductSpecifications/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productSpecification = await _context.ProductSpecifications
                .Include(p => p.Product)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (productSpecification == null)
            {
                return NotFound();
            }

            return View(productSpecification);
        }

        // POST: ProductSpecifications/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var productSpecification = await _context.ProductSpecifications.FindAsync(id);
            _context.ProductSpecifications.Remove(productSpecification);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductSpecificationExists(int id)
        {
            return _context.ProductSpecifications.Any(e => e.Id == id);
        }
    }
}

Views/Products/CategoryProducts.cshtml
@model IEnumerable<Supplier.Models.Product>
@{
    ViewData["Title"] = "Products";
    Layout = "~/Views/Shared/NewFolder/_Layout.cshtml";
}
<!-- Bootstrap core CSS -->
<link href="~/css/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

<!-- Page Content -->
<div class="container">

    <div class="row">

        <div class="col-lg-3">

            <h1 class="my-4">@ViewBag.Text</h1>
            @*<h3>> @Html.DisplayFor()</h3>*@
            <div class="list-group">
                @foreach (var item in Model)
                {

                    <a asp-controller="Products" asp-action="Details" asp-route-id="@item.Id"> @Html.DisplayFor(model => item.Name)</a>
                }
            </div>

        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">

            <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

            <div class="row">
                <!--card-->
                @foreach (var item in Model)
                {

                    <div class="col-lg-4 col-md-6 mb-4">
                        <div class="card h-100">


                            <a asp-controller="Products" asp-action="Details" asp-route-id="@item.Id">
                                <img class="card-img-top" src="@("~/image/"+item.ImageName)" asp-append-version="true" alt="asasa">
                            </a>

                            <div class="card-body">
                                <h4 class="card-title">
                                    <a asp-controller="Products" asp-action="Details" asp-route-id="@item.Id"> @Html.DisplayFor(model => item.Name)</a>
                                </h4>

                                <p class="card-text">
                                    @Html.DisplayFor(model => item.Description)
                                </p>
                            </div>
                            <div class="card-footer">
                                <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                            </div>
                        </div>
                    </div>

                }

                <!--end of card -->




            </div>
            <!-- /.row -->

        </div>
        <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->

</div>
<!-- /.container -->

Views/Products/Create.cshtml
@model Supplier.Models.Product

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/NavbarAdmin.cshtml";}

    <h4>Creating new Product</h4>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input required asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input required asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="ProductionDate" class="control-label"></label>
                <input  required asp-for="ProductionDate" class="form-control" />
                <span asp-validation-for="ProductionDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExpireDate" class="control-label"></label>
                <input  required asp-for="ExpireDate" class="form-control" />
                <span asp-validation-for="ExpireDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input required asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageFile" class="control-label"></label>
                <input required asp-for="ImageFile" accept="image/*" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Products/Delete.cshtml
@model Supplier.Models.Product

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/NavbarAdmin.cshtml";}

    <h4>Deleting Product: @Html.DisplayFor(model => model.Name)</h4>

<div>
    
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name):
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description):
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ProductionDate):
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ProductionDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ExpireDate):
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ExpireDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Amount):
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price):
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        @*<dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageFile)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageFile)
        </dd>*@
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Products/Details.cshtml
@model Supplier.Models.Product

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/NavbarAdmin.cshtml";}

<h4>Details for Product: @Html.DisplayFor(model => model.Name)</h4>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description):
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name):
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ProductionDate):
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ProductionDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ExpireDate):
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ExpireDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Amount):
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price):
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt class="col-sm-2">
            Specifications :
        </dt>
        <dd class="col-sm-10">

        </dd>

        <dt></dt>
        @foreach (var item in Model.ProductSpecifications)
        {
            <dt class="col-sm-2">

            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => item.value)
            </dd>
        }
        @*<dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.ImageFile)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.ImageFile)
            </dd>*@
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Products/Edit.cshtml
@model Supplier.Models.Product

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/NavbarAdmin.cshtml";}


<h4>Editing Product: @Html.DisplayFor(model => model.Name)</h4>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label">Product Name:</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Description:</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="ProductionDate" class="control-label">Production Date:</label>
                <input asp-for="ProductionDate" class="form-control" />
                <span asp-validation-for="ProductionDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExpireDate" class="control-label">Expire Date:</label>
                <input asp-for="ExpireDate" class="form-control" />
                <span asp-validation-for="ExpireDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label">Amount:</label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label">Price:</label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <!--<div class="form-group">
                <label asp-for="ImageFile" class="control-label"></label>
                <input asp-for="ImageFile" class="form-control" />
                <span asp-validation-for="ImageFile" class="text-danger"></span>
            </div>-->
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Products/Index.cshtml
@model IEnumerable<Supplier.Models.Product>

@{
    ViewData["Title"] = "Products";
    Layout = "~/Views/Shared/NavbarAdmin.cshtml";
}

<p>
    <a class="btn btn-primary" asp-action="Create">Create New Product</a>
</p>
<div id="dataDiv" style=" margin-left:10px; padding:5px;">
    <table id="customerDatatable" class="table table-striped table-bordered dt-responsive nowrap" width="100%" cellspacing="0">
        <thead>
            <tr>
                <th>
                    Product Name
                </th>
                <th>
                    Product Description
                </th>
              
                <th>
                    Actions
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">
                             <i class="far fa-edit fa-lg text-dark"></i><!--For Edit-->
                        </a> |
                        <a asp-action="Details" asp-route-id="@item.Id">
                             <i style="color:blue;" class="far fa-lg fa-question-circle"></i><!--For Details-->
                        </a>  |
                        <a asp-action="Delete" asp-route-id="@item.Id">
                            <i class="far fa-trash-alt fa-lg text-danger"></i><!--For Delete-->
                        </a> |
                        <a asp-action="Create" asp-controller="ProductSpecifications" asp-route-id="@item.Id">Add Specification</a> |
                        <a asp-action="IndexForId" asp-controller="ProductSpecifications" asp-route-id="@item.Id">Show Specifications</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
@section Scripts
{
    <script src="~/lib/datatables/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/datatables/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/js/customerDatatable.js"></script>
    <script>
    $(document).ready(function () {
            $('#customerDatatable').dataTable({
            });
        });</script>
}